"""A wiki page in, a Markdown volume out: chrome dropped, structure kept."""

from pathlib import Path

from library_agent.ingest.extract import SUPPORTED, extract
from library_agent.ingest.html import to_markdown

CONFLUENCE = """<!DOCTYPE html><html><head><title>Cassandra Ops : Compaction Strategies</title></head>
<body>
<div id="page">
<div id="main-header"><div id="breadcrumb-section"><ol id="breadcrumbs"><li><a href="index.html">Cassandra Ops</a></li></ol></div>
<h1 id="title-heading" class="pagetitle"><span id="title-text">Cassandra Ops : Compaction Strategies</span></h1></div>
<div id="content" class="view">
<div class="page-metadata">Created by ops-team, last modified on Jan 12, 2026</div>
<div id="main-content" class="wiki-content group">
<p>Compaction merges SSTables. Choose the strategy by <strong>workload</strong>.</p>
<h2 id="CompactionStrategies-STCS">Size-tiered</h2>
<p>Default. Good for write-heavy tables.</p>
<ul><li>min_threshold 4</li><li>max_threshold 32</li></ul>
<h2 id="CompactionStrategies-LCS">Leveled</h2>
<p>Read-heavy. Set it with:</p>
<div class="code panel pdl"><div class="codeContent panelContent pdl">
<pre class="syntaxhighlighter-pre" data-syntaxhighlighter-params="brush: sql; gutter: false">ALTER TABLE t WITH compaction = {'class': 'LeveledCompactionStrategy'};</pre>
</div></div>
<table class="confluenceTable"><tbody><tr><th>Strategy</th><th>Best for</th></tr>
<tr><td>STCS</td><td>writes</td></tr><tr><td>LCS</td><td>reads</td></tr></tbody></table>
</div>
<div class="pageSection group"><div class="pageSectionHeader"><h2 id="attachments" class="pageSectionTitle">Attachments:</h2></div><p>diagram.png</p></div>
</div>
<div id="footer" role="contentinfo"><section class="footer-body"><p>Document generated by Confluence on Jan 20, 2026</p></section></div>
</div></body></html>"""


def test_confluence_page_becomes_markdown():
    md, title = to_markdown(CONFLUENCE)
    assert title == "Compaction Strategies"
    assert md.startswith("# Compaction Strategies\n")
    assert "## Size-tiered" in md and "## Leveled" in md
    assert "- min_threshold 4" in md
    assert "```sql\nALTER TABLE t WITH compaction" in md
    assert "| Strategy | Best for |" in md
    assert "**workload**" in md
    # chrome is gone
    for junk in ("breadcrumb", "Created by ops-team", "Attachments", "generated by Confluence"):
        assert junk not in md


def test_html_is_a_supported_markdown_volume(tmp_path: Path):
    p = tmp_path / "compaction.html"
    p.write_text(CONFLUENCE)
    assert ".html" in SUPPORTED
    ex = extract(p)
    assert ex.title == "Compaction Strategies"
    assert [t.title for t in ex.toc] == ["Compaction Strategies", "Size-tiered", "Leveled"]
    assert ex.page_count == 1


def test_plain_page_without_landmarks():
    md, title = to_markdown(
        "<html><head><title>Runbook - Wiki</title></head><body><p>Restart the node.</p></body></html>"
    )
    assert title == "Runbook"
    assert "Restart the node." in md
