"""incidents

Revision ID: 0ba1bb43f341
Revises: 869267a64878
Create Date: 2026-09-19 03:27:18.182841

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '0ba1bb43f341'
down_revision: Union[str, Sequence[str], None] = '869267a64878'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('incident',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('source', sa.String(length=16), nullable=False),
    sa.Column('kind', sa.String(length=80), nullable=False),
    sa.Column('message', sa.Text(), nullable=False),
    sa.Column('detail', sa.Text(), nullable=True),
    sa.Column('context', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('count', sa.Integer(), nullable=False),
    sa.Column('first_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('last_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('resolved', sa.Boolean(), nullable=False),
    sa.Column('advice', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('advice_at', sa.DateTime(timezone=True), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_incident_kind'), 'incident', ['kind'], unique=False)
    op.create_index(op.f('ix_incident_resolved'), 'incident', ['resolved'], unique=False)
    op.create_index(op.f('ix_incident_source'), 'incident', ['source'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_incident_source'), table_name='incident')
    op.drop_index(op.f('ix_incident_resolved'), table_name='incident')
    op.drop_index(op.f('ix_incident_kind'), table_name='incident')
    op.drop_table('incident')
    # ### end Alembic commands ###
