"""cartridge_document.introduced

Revision ID: 413ba81872da
Revises: abe40d2da9b6
Create Date: 2026-09-19 01:36:16.091181

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '413ba81872da'
down_revision: Union[str, Sequence[str], None] = 'abe40d2da9b6'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('cartridge_document', sa.Column('introduced', sa.Boolean(), nullable=False, server_default=sa.false()))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('cartridge_document', 'introduced')
    # ### end Alembic commands ###
