"""initial schema

Revision ID: 51183c8ac0de
Revises: 
Create Date: 2026-09-18 15:38:59.987778

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
import pgvector.sqlalchemy
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '51183c8ac0de'
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    op.execute("CREATE EXTENSION IF NOT EXISTS vector")
    op.execute("CREATE EXTENSION IF NOT EXISTS pg_trgm")
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('artifact',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('kind', sa.String(length=24), nullable=False),
    sa.Column('target_kind', sa.String(length=16), nullable=False),
    sa.Column('target_id', sa.Uuid(), nullable=False),
    sa.Column('text', sa.Text(), nullable=False),
    sa.Column('data', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('model', sa.String(length=64), nullable=False),
    sa.Column('prompt_version', sa.String(length=16), nullable=False),
    sa.Column('tier', sa.SmallInteger(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('kind', 'target_kind', 'target_id', name='uq_artifact_target')
    )
    op.create_index(op.f('ix_artifact_kind'), 'artifact', ['kind'], unique=False)
    op.create_index(op.f('ix_artifact_target_id'), 'artifact', ['target_id'], unique=False)
    op.create_table('category',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('name', sa.Text(), nullable=False),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('merged_from', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('canonical', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('name')
    )
    op.create_table('cluster',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('label', sa.Text(), nullable=True),
    sa.Column('method', sa.String(length=32), nullable=False),
    sa.Column('size', sa.Integer(), nullable=False),
    sa.Column('document_count', sa.Integer(), nullable=False),
    sa.Column('has_contradiction', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('conversation',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('title', sa.Text(), nullable=True),
    sa.Column('conversational', sa.Boolean(), nullable=False),
    sa.Column('category_ids', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('document',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('content_hash', sa.String(length=64), nullable=False),
    sa.Column('title', sa.Text(), nullable=False),
    sa.Column('authors', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('kind', sa.String(length=16), nullable=False),
    sa.Column('source_path', sa.Text(), nullable=False),
    sa.Column('original_filename', sa.Text(), nullable=False),
    sa.Column('page_count', sa.Integer(), nullable=True),
    sa.Column('doi', sa.Text(), nullable=True),
    sa.Column('tier', sa.SmallInteger(), nullable=False),
    sa.Column('status', sa.String(length=16), nullable=False),
    sa.Column('starred', sa.Boolean(), nullable=False),
    sa.Column('retrieval_hits', sa.Integer(), nullable=False),
    sa.Column('near_dup_of', sa.Uuid(), nullable=True),
    sa.Column('error', sa.Text(), nullable=True),
    sa.Column('added_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['near_dup_of'], ['document.id'], ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_document_content_hash'), 'document', ['content_hash'], unique=True)
    op.create_index(op.f('ix_document_doi'), 'document', ['doi'], unique=False)
    op.create_index(op.f('ix_document_tier'), 'document', ['tier'], unique=False)
    op.create_table('embedding',
    sa.Column('owner_kind', sa.String(length=16), nullable=False),
    sa.Column('owner_id', sa.Uuid(), nullable=False),
    sa.Column('model', sa.String(length=64), nullable=False),
    sa.Column('vec', pgvector.sqlalchemy.halfvec.HALFVEC(dim=1024), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('owner_kind', 'owner_id', 'model')
    )
    op.create_index('ix_embedding_hnsw', 'embedding', ['vec'], unique=False, postgresql_using='hnsw', postgresql_ops={'vec': 'halfvec_cosine_ops'}, postgresql_with={'m': 16, 'ef_construction': 64})
    op.create_index('ix_embedding_lookup', 'embedding', ['owner_kind', 'model'], unique=False)
    op.create_table('eval_run',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('suite', sa.String(length=32), nullable=False),
    sa.Column('params', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('metrics', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('notes', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_eval_run_suite'), 'eval_run', ['suite'], unique=False)
    op.create_table('citation',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('citing_document_id', sa.Uuid(), nullable=False),
    sa.Column('matched_document_id', sa.Uuid(), nullable=True),
    sa.Column('raw_reference', sa.Text(), nullable=False),
    sa.Column('doi', sa.Text(), nullable=True),
    sa.Column('confidence', sa.Float(), nullable=False),
    sa.ForeignKeyConstraint(['citing_document_id'], ['document.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['matched_document_id'], ['document.id'], ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_citation_citing_document_id'), 'citation', ['citing_document_id'], unique=False)
    op.create_index(op.f('ix_citation_matched_document_id'), 'citation', ['matched_document_id'], unique=False)
    op.create_table('cluster_member',
    sa.Column('cluster_id', sa.Uuid(), nullable=False),
    sa.Column('artifact_id', sa.Uuid(), nullable=False),
    sa.Column('document_id', sa.Uuid(), nullable=False),
    sa.Column('distance', sa.Float(), nullable=False),
    sa.ForeignKeyConstraint(['artifact_id'], ['artifact.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['cluster_id'], ['cluster.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['document_id'], ['document.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('cluster_id', 'artifact_id')
    )
    op.create_index(op.f('ix_cluster_member_document_id'), 'cluster_member', ['document_id'], unique=False)
    op.create_table('document_category',
    sa.Column('document_id', sa.Uuid(), nullable=False),
    sa.Column('category_id', sa.Uuid(), nullable=False),
    sa.Column('confidence', sa.Float(), nullable=False),
    sa.ForeignKeyConstraint(['category_id'], ['category.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['document_id'], ['document.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('document_id', 'category_id')
    )
    op.create_table('job',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('kind', sa.String(length=32), nullable=False),
    sa.Column('document_id', sa.Uuid(), nullable=True),
    sa.Column('tier', sa.SmallInteger(), nullable=True),
    sa.Column('state', sa.String(length=16), nullable=False),
    sa.Column('progress_current', sa.Integer(), nullable=False),
    sa.Column('progress_total', sa.Integer(), nullable=False),
    sa.Column('yielded_reason', sa.Text(), nullable=True),
    sa.Column('error', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['document_id'], ['document.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_job_document_id'), 'job', ['document_id'], unique=False)
    op.create_index(op.f('ix_job_kind'), 'job', ['kind'], unique=False)
    op.create_index(op.f('ix_job_state'), 'job', ['state'], unique=False)
    op.create_table('message',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('conversation_id', sa.Uuid(), nullable=False),
    sa.Column('role', sa.String(length=16), nullable=False),
    sa.Column('content', sa.Text(), nullable=False),
    sa.Column('sources', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('rewritten_query', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['conversation_id'], ['conversation.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_message_conversation_id'), 'message', ['conversation_id'], unique=False)
    op.create_table('section',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('document_id', sa.Uuid(), nullable=False),
    sa.Column('parent_id', sa.Uuid(), nullable=True),
    sa.Column('order_index', sa.Integer(), nullable=False),
    sa.Column('path', sa.Text(), nullable=False),
    sa.Column('title', sa.Text(), nullable=True),
    sa.Column('level', sa.SmallInteger(), nullable=False),
    sa.Column('char_start', sa.Integer(), nullable=False),
    sa.Column('char_end', sa.Integer(), nullable=False),
    sa.Column('page_start', sa.Integer(), nullable=True),
    sa.Column('page_end', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['document_id'], ['document.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['parent_id'], ['section.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('ix_section_doc_order', 'section', ['document_id', 'order_index'], unique=False)
    op.create_index(op.f('ix_section_document_id'), 'section', ['document_id'], unique=False)
    op.create_table('chunk',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('document_id', sa.Uuid(), nullable=False),
    sa.Column('section_id', sa.Uuid(), nullable=True),
    sa.Column('order_index', sa.Integer(), nullable=False),
    sa.Column('text', sa.Text(), nullable=False),
    sa.Column('context_prefix', sa.Text(), nullable=False),
    sa.Column('token_count', sa.Integer(), nullable=False),
    sa.Column('page_start', sa.Integer(), nullable=True),
    sa.Column('char_start', sa.Integer(), nullable=False),
    sa.Column('char_end', sa.Integer(), nullable=False),
    sa.Column('fts', postgresql.TSVECTOR(), sa.Computed("to_tsvector('english', coalesce(context_prefix,'') || ' ' || text)", persisted=True), nullable=False),
    sa.ForeignKeyConstraint(['document_id'], ['document.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['section_id'], ['section.id'], ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('ix_chunk_doc_order', 'chunk', ['document_id', 'order_index'], unique=False)
    op.create_index(op.f('ix_chunk_document_id'), 'chunk', ['document_id'], unique=False)
    op.create_index('ix_chunk_fts', 'chunk', ['fts'], unique=False, postgresql_using='gin')
    op.create_index(op.f('ix_chunk_section_id'), 'chunk', ['section_id'], unique=False)
    op.create_table('chunk_category',
    sa.Column('chunk_id', sa.Uuid(), nullable=False),
    sa.Column('category_id', sa.Uuid(), nullable=False),
    sa.Column('confidence', sa.Float(), nullable=False),
    sa.ForeignKeyConstraint(['category_id'], ['category.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['chunk_id'], ['chunk.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('chunk_id', 'category_id')
    )
    op.create_table('eval_question',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('suite', sa.String(length=32), nullable=False),
    sa.Column('question', sa.Text(), nullable=False),
    sa.Column('gold_chunk_id', sa.Uuid(), nullable=True),
    sa.Column('gold_document_id', sa.Uuid(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['gold_chunk_id'], ['chunk.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['gold_document_id'], ['document.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_eval_question_suite'), 'eval_question', ['suite'], unique=False)
    op.create_table('eval_result',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('run_id', sa.Uuid(), nullable=False),
    sa.Column('question_id', sa.Uuid(), nullable=False),
    sa.Column('rank', sa.Integer(), nullable=True),
    sa.Column('score', sa.Float(), nullable=True),
    sa.Column('answer', sa.Text(), nullable=True),
    sa.Column('detail', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.CheckConstraint('rank is null or rank >= 1', name='ck_eval_rank_positive'),
    sa.ForeignKeyConstraint(['question_id'], ['eval_question.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['run_id'], ['eval_run.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_eval_result_run_id'), 'eval_result', ['run_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_eval_result_run_id'), table_name='eval_result')
    op.drop_table('eval_result')
    op.drop_index(op.f('ix_eval_question_suite'), table_name='eval_question')
    op.drop_table('eval_question')
    op.drop_table('chunk_category')
    op.drop_index(op.f('ix_chunk_section_id'), table_name='chunk')
    op.drop_index('ix_chunk_fts', table_name='chunk', postgresql_using='gin')
    op.drop_index(op.f('ix_chunk_document_id'), table_name='chunk')
    op.drop_index('ix_chunk_doc_order', table_name='chunk')
    op.drop_table('chunk')
    op.drop_index(op.f('ix_section_document_id'), table_name='section')
    op.drop_index('ix_section_doc_order', table_name='section')
    op.drop_table('section')
    op.drop_index(op.f('ix_message_conversation_id'), table_name='message')
    op.drop_table('message')
    op.drop_index(op.f('ix_job_state'), table_name='job')
    op.drop_index(op.f('ix_job_kind'), table_name='job')
    op.drop_index(op.f('ix_job_document_id'), table_name='job')
    op.drop_table('job')
    op.drop_table('document_category')
    op.drop_index(op.f('ix_cluster_member_document_id'), table_name='cluster_member')
    op.drop_table('cluster_member')
    op.drop_index(op.f('ix_citation_matched_document_id'), table_name='citation')
    op.drop_index(op.f('ix_citation_citing_document_id'), table_name='citation')
    op.drop_table('citation')
    op.drop_index(op.f('ix_eval_run_suite'), table_name='eval_run')
    op.drop_table('eval_run')
    op.drop_index('ix_embedding_lookup', table_name='embedding')
    op.drop_index('ix_embedding_hnsw', table_name='embedding', postgresql_using='hnsw', postgresql_ops={'vec': 'halfvec_cosine_ops'}, postgresql_with={'m': 16, 'ef_construction': 64})
    op.drop_table('embedding')
    op.drop_index(op.f('ix_document_tier'), table_name='document')
    op.drop_index(op.f('ix_document_doi'), table_name='document')
    op.drop_index(op.f('ix_document_content_hash'), table_name='document')
    op.drop_table('document')
    op.drop_table('conversation')
    op.drop_table('cluster')
    op.drop_table('category')
    op.drop_index(op.f('ix_artifact_target_id'), table_name='artifact')
    op.drop_index(op.f('ix_artifact_kind'), table_name='artifact')
    op.drop_table('artifact')
    # ### end Alembic commands ###
