"""cartridge design and art

Revision ID: 5bbfdac4a146
Revises: 0ba1bb43f341
Create Date: 2026-09-19 04:18:45.055665

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '5bbfdac4a146'
down_revision: Union[str, Sequence[str], None] = '0ba1bb43f341'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('cartridge', sa.Column('design', postgresql.JSONB(astext_type=sa.Text()), nullable=True))
    op.add_column('cartridge', sa.Column('art_path', sa.Text(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('cartridge', 'art_path')
    op.drop_column('cartridge', 'design')
    # ### end Alembic commands ###
