"""two-level shelf

Revision ID: 869267a64878
Revises: 413ba81872da
Create Date: 2026-09-19 02:06:10.055858

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '869267a64878'
down_revision: Union[str, Sequence[str], None] = '413ba81872da'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('category', sa.Column('parent_id', sa.Uuid(), nullable=True))
    op.create_index(op.f('ix_category_parent_id'), 'category', ['parent_id'], unique=False)
    op.create_foreign_key(None, 'category', 'category', ['parent_id'], ['id'], ondelete='SET NULL')
    op.add_column('document', sa.Column('shelf_id', sa.Uuid(), nullable=True))
    op.create_index(op.f('ix_document_shelf_id'), 'document', ['shelf_id'], unique=False)
    op.create_foreign_key(None, 'document', 'category', ['shelf_id'], ['id'], ondelete='SET NULL')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    # WARNING: constraint name is None; this directive will fail as
    # rendered.  Add a name, or use a naming convention; see
    # https://alembic.sqlalchemy.org/en/latest/naming.html
    op.drop_constraint(None, 'document', type_='foreignkey')
    op.drop_index(op.f('ix_document_shelf_id'), table_name='document')
    op.drop_column('document', 'shelf_id')
    # WARNING: constraint name is None; this directive will fail as
    # rendered.  Add a name, or use a naming convention; see
    # https://alembic.sqlalchemy.org/en/latest/naming.html
    op.drop_constraint(None, 'category', type_='foreignkey')
    op.drop_index(op.f('ix_category_parent_id'), table_name='category')
    op.drop_column('category', 'parent_id')
    # ### end Alembic commands ###
