"""cartridges

Revision ID: abe40d2da9b6
Revises: b1f3a9c0d2e4
Create Date: 2026-09-19 01:30:18.255151

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = 'abe40d2da9b6'
down_revision: Union[str, Sequence[str], None] = 'b1f3a9c0d2e4'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('cartridge',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('name', sa.Text(), nullable=False),
    sa.Column('slug', sa.String(length=80), nullable=False),
    sa.Column('version', sa.Integer(), nullable=False),
    sa.Column('colour', sa.String(length=16), nullable=False),
    sa.Column('icon_svg', sa.Text(), nullable=True),
    sa.Column('made_by', sa.Text(), nullable=True),
    sa.Column('made_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('level', sa.String(length=16), nullable=False),
    sa.Column('embed_model', sa.String(length=64), nullable=False),
    sa.Column('reader_model', sa.String(length=64), nullable=True),
    sa.Column('prompt_versions', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('manifest', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('content_hash', sa.String(length=64), nullable=False),
    sa.Column('document_count', sa.Integer(), nullable=False),
    sa.Column('imported_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_cartridge_slug'), 'cartridge', ['slug'], unique=False)
    op.create_table('cartridge_document',
    sa.Column('cartridge_id', sa.Uuid(), nullable=False),
    sa.Column('document_id', sa.Uuid(), nullable=False),
    sa.ForeignKeyConstraint(['cartridge_id'], ['cartridge.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['document_id'], ['document.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('cartridge_id', 'document_id')
    )
    op.add_column('artifact', sa.Column('cartridge_id', sa.Uuid(), nullable=True))
    op.drop_constraint(op.f('uq_artifact_target'), 'artifact', type_='unique')
    op.create_unique_constraint('uq_artifact_target', 'artifact', ['kind', 'target_kind', 'target_id', 'cartridge_id'], postgresql_nulls_not_distinct=True)
    op.create_index(op.f('ix_artifact_cartridge_id'), 'artifact', ['cartridge_id'], unique=False)
    op.create_foreign_key(None, 'artifact', 'cartridge', ['cartridge_id'], ['id'], ondelete='SET NULL')
    op.add_column('conversation', sa.Column('cartridge_ids', postgresql.JSONB(astext_type=sa.Text()), nullable=True))
    op.add_column('document', sa.Column('readings_only', sa.Boolean(), nullable=False, server_default=sa.false()))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('document', 'readings_only')
    op.drop_column('conversation', 'cartridge_ids')
    # WARNING: constraint name is None; this directive will fail as
    # rendered.  Add a name, or use a naming convention; see
    # https://alembic.sqlalchemy.org/en/latest/naming.html
    op.drop_constraint(None, 'artifact', type_='foreignkey')
    op.drop_index(op.f('ix_artifact_cartridge_id'), table_name='artifact')
    op.drop_constraint('uq_artifact_target', 'artifact', type_='unique')
    op.create_unique_constraint(op.f('uq_artifact_target'), 'artifact', ['kind', 'target_kind', 'target_id'], postgresql_nulls_not_distinct=False)
    op.drop_column('artifact', 'cartridge_id')
    op.drop_table('cartridge_document')
    op.drop_index(op.f('ix_cartridge_slug'), table_name='cartridge')
    op.drop_table('cartridge')
    # ### end Alembic commands ###
