"""Central configuration. Everything tunable lives here, nothing is hardcoded downstream."""

from functools import lru_cache
from pathlib import Path

from pydantic import Field
from pydantic_settings import BaseSettings, SettingsConfigDict


class Settings(BaseSettings):
    model_config = SettingsConfigDict(env_prefix="LIBRARY_", env_file=".env", extra="ignore")

    # --- storage ---
    database_url: str = "postgresql+psycopg://localhost:5432/library_agent"
    redis_url: str = "redis://localhost:6379/0"
    storage_dir: Path = Path.home() / ".library-agent" / "documents"

    # --- ollama / models ---
    # Point this at a remote instance and every model call follows it. The reranker is
    # the one exception: it runs in-process via torch and stays on the API host.
    ollama_url: str = "http://localhost:11434"
    # Sent as "Authorization: Bearer ..." when set. Ollama itself has no auth; this is for
    # a reverse proxy in front of a remote instance exposed beyond LAN/Tailscale.
    ollama_api_key: str | None = None
    # One generative model for everything. The planned "small fast reader + strong chat
    # model" split was measured and rejected: qwen3:4b ran 4.3s/section against 3.5s for
    # the 30B MoE (~3B active), so the small model was slower AND weaker AND cost extra
    # RAM. These stay separate fields so a future corpus can split them again, but they
    # should normally point at the same model.
    # Reading models are deliberately NOT user-switchable. Artifacts generated by
    # different models drift in style and granularity, which shows up as inconsistent
    # retrieval across the corpus. Pin one; artifact.model records it either way.
    reader_model: str = "qwen3:30b-a3b"
    deep_reader_model: str = "qwen3:30b-a3b"

    # Chat model is switchable per conversation. Both options are ~19GB and cannot be
    # co-resident on a 48GB machine, so switching costs a ~8-10s model swap.
    chat_model: str = "qwen3:30b-a3b"
    chat_model_options: dict[str, str] = Field(
        default_factory=lambda: {
            "general": "qwen3:30b-a3b",
            "technical": "huihui_ai/qwen3-coder-abliterated:latest",
        }
    )
    # Release the ~19GB when idle rather than pinning it. This machine sits at ~34GB used
    # before any model loads, and cold start measured only 8.1s -- not worth owning the
    # memory full time. "-1" would pin forever; "0" unloads immediately.
    keep_alive: str = "30m"
    embed_model: str = "bge-m3"
    embed_dim: int = 1024
    reranker_model: str = "BAAI/bge-reranker-v2-m3"

    # --- chunking ---
    chunk_target_tokens: int = 600
    chunk_overlap_ratio: float = 0.12
    chunk_min_tokens: int = 80  # merge trailing runts into the previous chunk
    # Below this many characters of text layer per page, treat the PDF as scanned.
    ocr_char_per_page_threshold: int = 120

    # --- retrieval ---
    router_top_documents: int = 15
    # Share of the candidate budget searched corpus-wide, so a router miss can't blind us.
    router_global_reserve: float = 0.20
    candidate_pool: int = 100
    final_top_k: int = 10
    # Measured: depth 20 matches depth 30 on recall@1/MRR while lifting recall@10 to
    # 0.985 (from 0.940 unreranked), at 1.2s vs 2.0s. Beyond 20 buys nothing.
    rerank_depth: int = 20
    # The cross-encoder helps paraphrased questions (+0.09 recall@1) and HURTS short
    # keyword queries (-0.035), which is why chat enables it and raw search does not.
    rerank_for_chat: bool = True

    # --- chat context budget ---
    # Time-to-first-token is dominated by prefill, and local prefill runs ~175 tok/s on
    # the 30B and ~300 tok/s on a 9.6GB model. Ten 600-token passages is ~4-6k tokens,
    # i.e. 15-25s before a single word appears. These two knobs are the only real lever.
    chat_passages: int = 5
    chat_passage_chars: int = 1200

    # Measured and rejected: see reading/tier1.py step 6. A document-constant orientation
    # line in every chunk prefix homogenises that document's vectors and costs recall.
    orientation_in_chunk_prefix: bool = False

    # Tier 2 reflections are NOT used for retrieval. Measured on two suites: on
    # chunk-derived questions MRR moved +0.005/-0.007, and on a purpose-built
    # *interpretive* suite -- the questions reflections exist for -- -0.022/+0.006. All
    # inside noise. Reflections remain valuable to read; they are not a retrieval signal.
    reflections_in_retrieval: bool = False
    rrf_k: int = 60
    # Measured, not guessed. Postgres ts_rank_cd has no IDF term, so the lexical half
    # injects noise from common words. On paraphrased questions it is a net loss at any
    # weight; on keyword queries it gains ~+0.035 MRR at 0.3. 0.2 is the compromise --
    # revisit once real query logs exist. See eval_run rows for the sweep.
    weight_lexical: float = 0.2
    weight_dense: float = 1.0

    # --- llm admission control ---
    # Chat holds a lease; reading yields between work units and waits out a quiet period.
    chat_lease_ttl_seconds: int = 60
    reading_resume_quiet_seconds: int = 120

    # --- library layer ---
    # Threads (clusters, citations, contradictions) derive from the whole collection, so
    # they go stale whenever a document is read. Rebuild automatically, but debounced:
    # one rebuild this long after the *last* read finishes, so a bulk import coalesces
    # into a single pass instead of one per document.
    library_rebuild_delay_seconds: int = 600

    # --- prompt versioning ---
    # Bumping a version marks matching artifacts stale so only those regenerate.
    prompt_versions: dict[str, str] = Field(
        default_factory=lambda: {
            "orientation": "v1",
            "section_summary": "v1",
            "document_summary": "v1",
            "categories": "v1",
            "reflection": "v1",
            "cluster_summary": "v1",
            "contradiction": "v1",
            "query_rewrite": "v1",
            "eval_question": "v1",
        }
    )


@lru_cache
def settings() -> Settings:
    return Settings()
